
export const GET_LIST_OF_ERRORS = "GET_LIST_OF_ERRORS";
export const LOADING = "LOADING";
export const SET_USER = "SET_USER";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_SUBJECT_BY_NAME = "DELETE_SUBJECT_BY_NAME";
export const DELETE_GROUP_BY_LABEL = "DELETE_GROUP_BY_LABEL";
export const SET_GENERATED_LIST = "SET_GENERATED_LIST";
export const SET_GROUP_BY_SUBJECT = "SET_GROUP_BY_SUBJECT";
export const SET_MIN_BREAK = "SET_MIN_BREAK";
export const SET_REFRESH = "SET_REFRESH";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SET_NO_CLASS = "SET_NO_CLASS";
export const SET_PROF_PREF = "SET_PROF_PREF";
export const REARRANGE_PROF = "REARRANGE_PROF";
export const SET_DISTRIBUTE_CLASSES = "SET_DISTRIBUTE_CLASSES";
export const INIT_SUBARRAY = "INIT_SUBARRAY"
export const INIT_GRPARRAY = "INIT_GRPARRAY"
export const SET_SELECTED_TABLE = "SET_SELECTED_TABLE"


